CREATE OR REPLACE VIEW VIEW_COMPLAINT (ID, SERVICE_NUMBER, CATEGORY_ID, SUB_CATEGORY_ID, RESCUE_ID, SECTION_ID, SERVICE_ADDRESS, 
LANDMARK, LATITUDE, LONGITUDE, IMAGE_1, IMAGE_2, DESCRIPTION, USER_ID,APPLICATION_NO, MOBILE, STATUS_ID, CREATED_ON, 
UPDATED_ON, REGION_ID, CIRCLE_ID, DEVICE, COMPLAINT_CODE, COMPLAINT_TYPE, FOC_COMPLAINT_ID, SUB_DIVISION_ID, 
DIVISION_ID, SECTION_NAME, CIRCLE_NAME, CATEGORY_NAME, SUB_CATEGORY_NAME, RATING) AS SELECT
COMP.ID,
COMP.SERVICE_NUMBER,
COMP.CATEGORY_ID,
COMP.SUB_CATEGORY_ID,
COMP.RESCUE_ID,
COMP.SECTION_ID,
COMP.SERVICE_ADDRESS,
COMP.LANDMARK,
COMP.LATITUDE,
COMP.LONGITUDE,
COMP.IMAGE_1,
COMP.IMAGE_2,
COMP.DESCRIPTION,
COMP.USER_ID,
COMP.APPLICATION_NO,
PU.MOBILE,
COMP.STATUS_ID,
COMP.CREATED_ON,
COMP.UPDATED_ON,
COMP.REGION_ID,
COMP.CIRCLE_ID,
COMP.DEVICE,
COMP.COMPLAINT_CODE,
COMP.COMPLAINT_TYPE,
COMP.FOC_COMPLAINT_ID,
VL.SUB_DIVISION_ID,
VL.DIVISION_ID,
VL.SECTION_NAME,
VL.CIRCLE_NAME,
C.NAME AS CATEGORY_NAME,
SC.NAME AS SUB_CATEGORY_NAME,
COMP.RATING
FROM
COMPLAINT COMP
INNER JOIN PUBLIC_USER PU ON COMP.USER_ID = PU.ID
INNER JOIN VIEW_LOCATION VL ON COMP.SECTION_ID = VL.SECTION_ID
INNER JOIN CATEGORY C ON COMP.CATEGORY_ID = C.ID
INNER JOIN SUB_CATEGORY SC ON COMP.SUB_CATEGORY_ID = SC.ID;