CREATE OR REPLACE VIEW VIEW_LOCATION (REGION_ID, REGION_NAME, CIRCLE_ID, CIRCLE_NAME, DIVISION_ID,
 DIVISION_NAME, SUB_DIVISION_ID, SUB_DIVISION_NAME, SECTION_ID, SECTION_NAME, SECTION_CODE)
AS SELECT
R.ID AS REGION_ID,
R.NAME AS REGION_NAME,
C.ID AS CIRCLE_ID,
C.NAME AS CIRCLE_NAME,
D.ID AS DIVISION_ID,
D.NAME AS DIVISION_NAME,
SD.ID AS SUB_DIVISION_ID,
SD.NAME AS SUB_DIVISION_NAME,
S.ID AS SECTION_ID,
S.NAME AS SECTION_NAME,
S.CODE AS SECTION_CODE
FROM
SECTION S
INNER JOIN SUB_DIVISION SD ON S.SUB_DIVISION_ID = SD.ID
INNER JOIN CIRCLE C ON S.CIRCLE_ID = C.ID
INNER JOIN DIVISION D ON S.DIVISION_ID = D.ID
INNER JOIN REGION R ON S.REGION_ID = R.ID;



CREATE OR REPLACE VIEW VIEW_COMPLAINT (ID, SERVICE_NUMBER, CATEGORY_ID, SUB_CATEGORY_ID, RESCUE_ID, SECTION_ID, SERVICE_ADDRESS,
 LANDMARK, LATITUDE, LONGITUDE, IMAGE_1, IMAGE_2, DESCRIPTION, USER_ID, MOBILE, STATUS_ID,
  CREATED_ON, UPDATED_ON, REGION_ID, CIRCLE_ID, DEVICE, COMPLAINT_CODE, COMPLAINT_TYPE, FOC_COMPLAINT_ID, SUB_DIVISION_ID, DIVISION_ID,
   SECTION_NAME, CIRCLE_NAME, CATEGORY_NAME, SUB_CATEGORY_NAME, RATING) 
AS SELECT
COMP.ID,
COMP.SERVICE_NUMBER,
COMP.CATEGORY_ID,
COMP.SUB_CATEGORY_ID,
COMP.RESCUE_ID,
COMP.SECTION_ID,
COMP.SERVICE_ADDRESS,
COMP.LANDMARK,
COMP.LATITUDE,
COMP.LONGITUDE,
COMP.IMAGE_1,
COMP.IMAGE_2,
COMP.DESCRIPTION,
COMP.USER_ID,
PU.MOBILE,
COMP.STATUS_ID,
COMP.CREATED_ON,
COMP.UPDATED_ON,
COMP.REGION_ID,
COMP.CIRCLE_ID,
COMP.DEVICE,
COMP.COMPLAINT_CODE,
COMP.COMPLAINT_TYPE,
COMP.FOC_COMPLAINT_ID,
VL.SUB_DIVISION_ID,
VL.DIVISION_ID,
VL.SECTION_NAME,
VL.CIRCLE_NAME,
C.NAME AS CATEGORY_NAME,
SC.NAME AS SUB_CATEGORY_NAME,
COMP.RATING
FROM
COMPLAINT COMP
INNER JOIN PUBLIC_USER PU ON COMP.USER_ID = PU.ID
INNER JOIN VIEW_LOCATION VL ON COMP.SECTION_ID = VL.SECTION_ID
INNER JOIN CATEGORY C ON COMP.CATEGORY_ID = C.ID
INNER JOIN SUB_CATEGORY SC ON COMP.SUB_CATEGORY_ID = SC.ID;



CREATE OR REPLACE VIEW VIEW_COMPLAINT_REMARK
as 
select chd.complaint_id, listagg(chd.complaint_description, ',') within group (order by chd.id) as remarks from 
(
select distinct ch.id, ch.complaint_id,  
decode(r.name, NULL, decode(ccr.name, null, 'Customer', (ccu.name || ' / ' || ccu.user_name)), (r.name || ' / ' || au.office_name)) || ' : ' || ch.description
 as complaint_description
  from complaint_history ch, public_user p, admin_user au, role r , call_center_user ccu, call_center_role ccr
where 
ch.public_user_id  = p.id (+) and
ch.admin_user_id = au.id (+) and
au.role_id = r.id (+) and
ch.call_user_id = ccu.id (+) and
ccu.role_id = ccr.id (+) 
order by ch.complaint_id , ch.id asc
) chd 
group by chd.complaint_id;



CREATE OR REPLACE VIEW VIEW_COMPLAINT_REPORT (ID, SERVICE_NUMBER, CATEGORY_ID, SUB_CATEGORY_ID, RESCUE_ID, SECTION_ID, SERVICE_ADDRESS,
 LANDMARK, LATITUDE, LONGITUDE, IMAGE_1, IMAGE_2, DESCRIPTION, USER_ID, MOBILE, STATUS_ID,
  CREATED_ON, UPDATED_ON, REGION_ID, CIRCLE_ID, DEVICE, COMPLAINT_CODE, COMPLAINT_TYPE, FOC_COMPLAINT_ID, SUB_DIVISION_ID, DIVISION_ID,
   SECTION_NAME, CIRCLE_NAME, CATEGORY_NAME, SUB_CATEGORY_NAME, RATING, REMARKS) 
AS SELECT
COMP.ID,
COMP.SERVICE_NUMBER,
COMP.CATEGORY_ID,
COMP.SUB_CATEGORY_ID,
COMP.RESCUE_ID,
COMP.SECTION_ID,
COMP.SERVICE_ADDRESS,
COMP.LANDMARK,
COMP.LATITUDE,
COMP.LONGITUDE,
COMP.IMAGE_1,
COMP.IMAGE_2,
COMP.DESCRIPTION,
COMP.USER_ID,
PU.MOBILE,
COMP.STATUS_ID,
COMP.CREATED_ON,
COMP.UPDATED_ON,
COMP.REGION_ID,
COMP.CIRCLE_ID,
COMP.DEVICE,
COMP.COMPLAINT_CODE,
COMP.COMPLAINT_TYPE,
COMP.FOC_COMPLAINT_ID,
VL.SUB_DIVISION_ID,
VL.DIVISION_ID,
VL.SECTION_NAME,
VL.CIRCLE_NAME,
C.NAME AS CATEGORY_NAME,
SC.NAME AS SUB_CATEGORY_NAME,
COMP.RATING,
VW_CR.REMARKS
FROM
COMPLAINT COMP
INNER JOIN VIEW_COMPLAINT_REMARK VW_CR ON COMP.ID = VW_CR.COMPLAINT_ID
INNER JOIN PUBLIC_USER PU ON COMP.USER_ID = PU.ID
INNER JOIN VIEW_LOCATION VL ON COMP.SECTION_ID = VL.SECTION_ID
INNER JOIN CATEGORY C ON COMP.CATEGORY_ID = C.ID
INNER JOIN SUB_CATEGORY SC ON COMP.SUB_CATEGORY_ID = SC.ID;








