--ROLE

CREATE SEQUENCE ROLE_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE ROLE (
	ID   				NUMBER(10)    CONSTRAINT NN_ROLE_ID NOT NULL,
	CODE 				VARCHAR2(10) CONSTRAINT NN_ROLE_CODE NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_ROLE_NAME NOT NULL,
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE ROLE ADD CONSTRAINT PK_ROLE_ID PRIMARY KEY (ID);

--REGION

CREATE SEQUENCE REGION_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE REGION (
	ID   				NUMBER(10)    CONSTRAINT NN_REGION_ID NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_REGION_NAME NOT NULL,
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE REGION ADD CONSTRAINT PK_REGION_ID PRIMARY KEY (ID);


--CIRCLE

CREATE SEQUENCE CIRCLE_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE CIRCLE (
	ID   				NUMBER(10) CONSTRAINT NN_CIRCLE_ID NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_CIRCLE_NAME NOT NULL,
   	CODE 				VARCHAR2(10) CONSTRAINT NN_CIRCLE_CODE NOT NULL,
   	IP_ADDRESS			VARCHAR2(20),
   	REGION_ID			NUMBER(10) NOT NULL CONSTRAINT FK_CIRCLE_REGION_ID REFERENCES REGION ON DELETE CASCADE,   	
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE CIRCLE ADD CONSTRAINT PK_CIRCLE_ID PRIMARY KEY (ID);

--DISTRICT

CREATE SEQUENCE DISTRICT_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE DISTRICT (
	ID 					NUMBER(10) CONSTRAINT NN_DISTRICT_ID NOT NULL,
	CODE				VARCHAR2(10) CONSTRAINT NN_DISTRICT_CODE NOT NULL,
	NAME				VARCHAR2(100) CONSTRAINT NN_DISTRICT_NAME NOT NULL,
	CIRCLE_CODE			VARCHAR2(10) CONSTRAINT NN_DISTRICT_CIRCLE_CODE NOT NULL,
	CIRCLE_NAME			VARCHAR2(100) CONSTRAINT NN_DISTRICT_CIRCLE_NAME NOT NULL,
	SECTION_CODE		VARCHAR2(10) CONSTRAINT NN_DISTRICT_SECTION_CODE NOT NULL,
	SECTION_NAME		VARCHAR2(100) CONSTRAINT NN_DISTRICT_SECTION_NAME NOT NULL,
	REGION_ID			NUMBER(10) CONSTRAINT FK_DISTRICT_REGION_ID REFERENCES REGION NOT NULL,
	CIRCLE_ID			NUMBER(10) CONSTRAINT FK_DISTRICT_CIRCLE_ID REFERENCES CIRCLE,
	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE DISTRICT ADD CONSTRAINT PK_DISTRICT_ID PRIMARY KEY (ID);


--DIVISION

CREATE SEQUENCE DIVISION_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE DIVISION (
	ID   				NUMBER(10) CONSTRAINT NN_DIVISION_ID NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_DIVISION_NAME NOT NULL,
   	CODE 				VARCHAR2(10) CONSTRAINT NN_DIVISION_CODE NOT NULL,
   	ADDRESS				VARCHAR2(500),
   	PIN_CODE   			NUMBER(6),
   	PHONE_NUMBER 		VARCHAR2(15),
   	MOBILE		 		VARCHAR2(10),
   	EMAIL				VARCHAR2(100),
   	REGION_ID			NUMBER(10) NOT NULL CONSTRAINT FK_DIVISION_REGION_ID REFERENCES REGION ON DELETE CASCADE,
   	CIRCLE_ID			NUMBER(10) NOT NULL CONSTRAINT FK_DIVISION_CIRCLE_ID REFERENCES CIRCLE ON DELETE CASCADE,
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE DIVISION ADD CONSTRAINT PK_DIVISION_ID PRIMARY KEY (ID);


--SUB DIVISION

CREATE SEQUENCE SUB_DIVISION_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE SUB_DIVISION (
	ID   				NUMBER(10) CONSTRAINT NN_SUB_DIVISION_ID NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_SUB_DIVISION_NAME NOT NULL,
   	CODE 				VARCHAR2(10) CONSTRAINT NN_SUB_DIVISION_CODE NOT NULL,
   	ADDRESS				VARCHAR2(500),
   	PHONE_NUMBER 		VARCHAR2(15),
   	MOBILE		 		VARCHAR2(10),
   	EMAIL				VARCHAR2(100),
   	REGION_ID			NUMBER(10) NOT NULL CONSTRAINT FK_SUB_DIVISION_REGION_ID REFERENCES REGION ON DELETE CASCADE,
   	CIRCLE_ID			NUMBER(10) NOT NULL CONSTRAINT FK_SUB_DIVISION_CIRCLE_ID REFERENCES CIRCLE ON DELETE CASCADE,
   	DIVISION_ID			NUMBER(10) NOT NULL CONSTRAINT FK_SUB_DIVISION_DIVISION_ID REFERENCES DIVISION ON DELETE CASCADE,
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE SUB_DIVISION ADD CONSTRAINT PK_SUB_DIVISION_ID PRIMARY KEY (ID);


--SECTION

CREATE SEQUENCE SECTION_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE SECTION (
	ID   				NUMBER(10) CONSTRAINT NN_SECTION_ID NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_SECTION_NAME NOT NULL,
   	CODE 				VARCHAR2(10) CONSTRAINT NN_SECTION_CODE NOT NULL,
   	ADDRESS				VARCHAR2(500),
   	PIN_CODE   			NUMBER(6),
   	PHONE_NUMBER 		VARCHAR2(15),
   	MOBILE		 		VARCHAR2(10),
   	EMAIL				VARCHAR2(100),
   	REGION_ID			NUMBER(10) NOT NULL CONSTRAINT FK_SECTION_REGION_ID REFERENCES REGION ON DELETE CASCADE,
   	CIRCLE_ID			NUMBER(10) NOT NULL CONSTRAINT FK_SECTION_CIRCLE_ID REFERENCES CIRCLE ON DELETE CASCADE,
   	DIVISION_ID			NUMBER(10) NOT NULL CONSTRAINT FK_SECTION_DIVISION_ID REFERENCES DIVISION ON DELETE CASCADE,
   	SUB_DIVISION_ID		NUMBER(10) NOT NULL CONSTRAINT FK_SECTION_SUB_DIVISION_ID REFERENCES SUB_DIVISION ON DELETE CASCADE,
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE SECTION ADD CONSTRAINT PK_SECTION_ID PRIMARY KEY (ID);


--ADMIN USER

CREATE SEQUENCE ADMIN_USER_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE ADMIN_USER (
	ID   				NUMBER(10) CONSTRAINT NN_ADMIN_USER_ID NOT NULL,
   	OFFICE_NAME 		VARCHAR2(100) CONSTRAINT NN_ADMIN_USER_OFFICE_NAME NOT NULL,
   	SECTION_CODE 		VARCHAR2(10),
   	USER_NAME			VARCHAR2(20) CONSTRAINT NN_ADMIN_USER_USER_NAME NOT NULL,
   	PASSWORD			VARCHAR2(100) CONSTRAINT NN_ADMIN_USER_PASSWORD NOT NULL,
   	MOBILE		 		VARCHAR2(10),
   	EMAIL				VARCHAR2(100),
   	ROLE_ID				NUMBER(10) NOT NULL CONSTRAINT FK_ADMIN_USER_ROLE_ID REFERENCES ROLE ON DELETE CASCADE,   
   	REGION_ID			NUMBER(10) NOT NULL CONSTRAINT FK_ADMIN_USER_REGION_ID REFERENCES REGION ON DELETE CASCADE,
   	CIRCLE_ID			NUMBER(10) NOT NULL CONSTRAINT FK_ADMIN_USER_CIRCLE_ID REFERENCES CIRCLE ON DELETE CASCADE,
   	DIVISION_ID			NUMBER(10) CONSTRAINT FK_ADMIN_USER_DIVISION_ID REFERENCES DIVISION,
   	SUB_DIVISION_ID		NUMBER(10) CONSTRAINT FK_ADMIN_USER_SUB_DIVISION_ID REFERENCES SUB_DIVISION,
   	SECTION_ID			NUMBER(10) CONSTRAINT FK_ADMIN_USER_SECTION_ID REFERENCES SECTION,
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE ADMIN_USER ADD CONSTRAINT PK_ADMIN_USER_ID PRIMARY KEY (ID);


--RESCUE

CREATE SEQUENCE RESCUE_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE RESCUE (
	ID 					NUMBER(10) CONSTRAINT NN_RESCUE_ID NOT NULL,
	NAME 				VARCHAR2(100) CONSTRAINT NN_RESCUE_NAME NOT NULL,
	CREATED_ON 			TIMESTAMP DEFAULT SYSDATE NOT NULL,
	UPDATED_ON 			TIMESTAMP DEFAULT SYSDATE NOT NULL
);


     
ALTER TABLE RESCUE ADD CONSTRAINT PK_RESCUE_ID PRIMARY KEY (ID);

--CATEGORY

CREATE SEQUENCE CATEGORY_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE CATEGORY (
	ID 					NUMBER(10) CONSTRAINT NN_CATEGORY_ID NOT NULL,
	NAME 				VARCHAR2(100) CONSTRAINT NN_CATEGORY_NAME NOT NULL,
	RESCUE_ID			NUMBER(10) NOT NULL CONSTRAINT FK_CATEGORY_RESCUE_ID REFERENCES RESCUE ON DELETE CASCADE,
	CREATED_ON 			TIMESTAMP DEFAULT SYSDATE NOT NULL,
	UPDATED_ON 			TIMESTAMP DEFAULT SYSDATE NOT NULL
);

     
ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY_ID PRIMARY KEY (ID);


--SUB_CATEGORY

CREATE SEQUENCE SUB_CATEGORY_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE SUB_CATEGORY (
	ID 					NUMBER(10) CONSTRAINT NN_SUB_CATEGORY_ID NOT NULL,
	NAME 				VARCHAR2(100) CONSTRAINT NN_SUB_CATEGORY_NAME NOT NULL,
	CATEGORY_ID			NUMBER(10) NOT NULL CONSTRAINT FK_SUB_CATEGORY_CATEGORY_ID REFERENCES CATEGORY ON DELETE CASCADE,
	CREATED_ON 			TIMESTAMP DEFAULT SYSDATE NOT NULL,
	UPDATED_ON 			TIMESTAMP DEFAULT SYSDATE NOT NULL
);

     
ALTER TABLE SUB_CATEGORY ADD CONSTRAINT PK_SUB_CATEGORY_ID PRIMARY KEY (ID);


--PUBLIC_USER

CREATE SEQUENCE PUBLIC_USER_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE PUBLIC_USER (
	ID   				NUMBER(10) CONSTRAINT NN_PUBLIC_USER_ID NOT NULL,
   	FIRST_NAME 			VARCHAR2(50) ,
   	LAST_NAME 			VARCHAR2(50) ,
   	MOBILE		 		VARCHAR2(10) CONSTRAINT NN_PUBLIC_USER_MOBILE NOT NULL,
   	EMAIL				VARCHAR2(100) ,
   	PASSWORD			VARCHAR2(100) ,
	ADDRESS				VARCHAR2(500) ,
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE PUBLIC_USER ADD CONSTRAINT PK_PUBLIC_USER_ID PRIMARY KEY (ID);


--CLOSURE_REASON

CREATE SEQUENCE CLOSURE_REASON_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;

CREATE TABLE CLOSURE_REASON (
		ID					NUMBER(10) CONSTRAINT NN_CLOSURE_REASON_ID NOT NULL,
		COMPLAINT_CODE		NUMBER(2) CONSTRAINT NN_CLOSURE_REASON_CC_CODE NOT NULL,
		REASON	 			VARCHAR2(250) CONSTRAINT NN_CLOSURE_REASON_REASON NOT NULL
);

ALTER TABLE CLOSURE_REASON ADD CONSTRAINT PK_CLOSURE_REASON_ID PRIMARY KEY (ID);


--COMPLAINT

CREATE SEQUENCE COMPLAINT_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE COMPLAINT (
	ID 					NUMBER(10) CONSTRAINT NN_COMP_ID NOT NULL,
	COMPLAINT_TYPE 		VARCHAR2(10) CONSTRAINT NN_COMP_COMPLAINT_TYPE NOT NULL, 
	DESCRIPTION 		VARCHAR2(250),
	SERVICE_NUMBER 		VARCHAR2(20), 
	LANDMARK 			VARCHAR2(100), 
	LATITUDE			VARCHAR2(50), 
	LONGITUDE 			VARCHAR2(50), 
	IMAGE_1 			VARCHAR2(250), 
	IMAGE_2 			VARCHAR2(250), 
	DEVICE 				VARCHAR2(20), 
	SERVICE_NAME 		VARCHAR2(100), 
	SERVICE_ADDRESS		VARCHAR2(500), 
	FOC_COMPLAINT_ID 	VARCHAR2(20), 
	COMPLAINT_CODE 		NUMBER(2),  
	STATUS_ID 			NUMBER(2), 
	RATING 				INTEGER DEFAULT 0,
	USER_ID 			NUMBER(10) NOT NULL CONSTRAINT FK_COMP_USER_ID REFERENCES PUBLIC_USER ON DELETE CASCADE, 
	RESCUE_ID 			NUMBER(2) CONSTRAINT FK_COMP_RESCUE_ID REFERENCES RESCUE, 	
	CATEGORY_ID 		NUMBER(2) CONSTRAINT FK_COMP_CATEGORY_ID REFERENCES CATEGORY,
	SUB_CATEGORY_ID 	NUMBER(2) CONSTRAINT FK_COMP_SUB_CATEGORY_ID REFERENCES SUB_CATEGORY,
	REGION_ID			NUMBER(10) CONSTRAINT FK_COMP_REGION_ID REFERENCES REGION,
	CIRCLE_ID 			NUMBER(10) CONSTRAINT FK_COMP_CIRCLE_ID REFERENCES CIRCLE,
	DIVISION_ID 		NUMBER(10) CONSTRAINT FK_COMP_DIVISION_ID REFERENCES DIVISION,
	SUB_DIVISION_ID 	NUMBER(10) CONSTRAINT FK_COMP_SUB_DIVISION_ID REFERENCES SUB_DIVISION, 
	SECTION_ID 			NUMBER(10) CONSTRAINT FK_COMP_SECTION_ID REFERENCES SECTION,
	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);

     
ALTER TABLE COMPLAINT ADD CONSTRAINT PK_COMPLAINT_ID PRIMARY KEY (ID);


--CALL CENTER ROLE

CREATE SEQUENCE CALL_CENTER_ROLE_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE CALL_CENTER_ROLE (
	ID   				NUMBER(10)    CONSTRAINT NN_CALL_CENTER_ROLE_ID NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_CALL_CENTER_ROLE_NAME NOT NULL,
   	CREATED_ON			TIMESTAMP	 DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP	 DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE CALL_CENTER_ROLE ADD CONSTRAINT PK_CALL_CENTER_ROLE_ID PRIMARY KEY (ID);

--CALL CENTER USER

CREATE SEQUENCE CALL_CENTER_USER_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE CALL_CENTER_USER (
	ID   				NUMBER(10) CONSTRAINT NN_CALL_CENTER_USER_ID NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_CALL_CENTER_NAME NOT NULL,  
   	USER_NAME			VARCHAR2(20) CONSTRAINT NN_CALL_CENTER_USER_NAME NOT NULL,
   	PASSWORD			VARCHAR2(100) CONSTRAINT NN_CALL_CENTER_PASSWORD NOT NULL,
   	MOBILE		 		VARCHAR2(10),
   	EMAIL				VARCHAR2(100),
   	ROLE_ID				NUMBER(10) NOT NULL CONSTRAINT FK_CALL_CENTER_ROLE_ID REFERENCES CALL_CENTER_ROLE ON DELETE CASCADE,
    CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE CALL_CENTER_USER ADD CONSTRAINT PK_CALL_CENTER_USER_ID PRIMARY KEY (ID);

--COMPLAINT_HISTORY

CREATE SEQUENCE COMPLAINT_HISTORY_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE COMPLAINT_HISTORY (
	ID   				NUMBER(10) CONSTRAINT NN_COMP_HIS_ID NOT NULL,
   	DESCRIPTION 		VARCHAR2(250) CONSTRAINT NN_COMP_HIS_DESCRIPTION NOT NULL,
   	STATUS_ID			NUMBER(2) CONSTRAINT NN_COMP_HIS_STATUS_ID NOT NULL,
   	COMPLAINT_ID		NUMBER(10) NOT NULL CONSTRAINT FK_COMP_HIS_COMPLAINT_ID REFERENCES COMPLAINT ON DELETE CASCADE,
   	REGION_ID			NUMBER(10) CONSTRAINT FK_COMP_HIS_REGION_ID REFERENCES REGION,
   	CIRCLE_ID			NUMBER(10) CONSTRAINT FK_COMP_HIS_CIRCLE_ID REFERENCES CIRCLE,
   	DIVISION_ID			NUMBER(10) CONSTRAINT FK_COMP_HIS_DIVISION_ID REFERENCES DIVISION,
   	SUB_DIVISION_ID		NUMBER(10) CONSTRAINT FK_COMP_HIS_SUB_DIVISION_ID REFERENCES SUB_DIVISION,
   	SECTION_ID			NUMBER(10) CONSTRAINT FK_COMP_HIS_SECTION_ID REFERENCES SECTION,
	ADMIN_USER_ID		NUMBER(10) CONSTRAINT FK_COMP_HIS_ADMIN_USER_ID REFERENCES ADMIN_USER,
	PUBLIC_USER_ID		NUMBER(10) CONSTRAINT FK_COMP_HIS_PUBLIC_USER_ID REFERENCES PUBLIC_USER,
	CALL_USER_ID		NUMBER(10) CONSTRAINT FK_COMP_HIS_CC_USER_ID REFERENCES CALL_CENTER_USER,
   	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE COMPLAINT_HISTORY ADD CONSTRAINT PK_COMPLAINT_HISTORY_ID PRIMARY KEY (ID);



--CONSUMER_SERVICE

CREATE SEQUENCE CONSUMER_SERVICE_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
CREATE TABLE CONSUMER_SERVICE (
	ID 					NUMBER(10) CONSTRAINT NN_CON_SERV_ID NOT NULL,
	USER_ID 			NUMBER(10) NOT NULL CONSTRAINT NN_CON_SERV_USER_ID REFERENCES PUBLIC_USER ON DELETE CASCADE, 
	SERVICE_NUMBER 		VARCHAR2(20), 
	SERVICE_TARIFF		VARCHAR2(50),
	SERVICE_NAME 		VARCHAR2(100), 
	SERVICE_ADDRESS		VARCHAR2(500), 
	LANDMARK 			VARCHAR2(100), 
	MOBILE 				VARCHAR2(10), 
	DIVISION_ID 		NUMBER(10) CONSTRAINT FK_CON_SERV_DIVISION_ID REFERENCES DIVISION,
	REGION_ID			NUMBER(10) CONSTRAINT FK_CON_SERV_REGION_ID REFERENCES REGION,
	CIRCLE_ID 			NUMBER(10) CONSTRAINT FK_CON_SERV_CIRCLE_ID REFERENCES CIRCLE,
	SUB_DIVISION_ID 	NUMBER(10) CONSTRAINT FK_CON_SERV_SUB_DIVISION_ID REFERENCES SUB_DIVISION, 
	SECTION_ID 			NUMBER(10) CONSTRAINT FK_CON_SERV_SECTION_ID REFERENCES SECTION,
	CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
  
     
ALTER TABLE CONSUMER_SERVICE ADD CONSTRAINT PK_CONSUMER_SERVICE_ID PRIMARY KEY (ID);


--SMSGS SEQUENCE

CREATE SEQUENCE SMSGS_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
 
--TABLE SMSGS
 
CREATE TABLE SMSGS (
	ID 	NUMBER(10) CONSTRAINT NN_SMSGS_ID NOT NULL,
	OTP VARCHAR2(10), 
	CUSCODE VARCHAR2(20) CONSTRAINT NN_SMSGS_CUSCODE NOT NULL, 
	ENTRYDT DATE CONSTRAINT NN_SMSGS_ENTRYDT NOT NULL, 
	MOBILENO VARCHAR2(20) CONSTRAINT NN_SMSGS_MOBILENO NOT NULL, 
	MSG VARCHAR2(200) CONSTRAINT NN_SMSGS_MSG NOT NULL, 
	SMS_SENT VARCHAR2(2), 
	TID VARCHAR2(100), 
	SMS_DT DATE, 
	STATUS VARCHAR2(30), 
	ERROR_CODE VARCHAR2(10), 
	SMS_DT2 DATE
);

ALTER TABLE SMSGS ADD CONSTRAINT PK_SMSGS_ID PRIMARY KEY (ID);


  

--FOC_COMPLAINT

CREATE SEQUENCE FOC_COMPLAINT_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE FOC_COMPLAINT (
	ID 						NUMBER(10) CONSTRAINT NN_FOC_COMPLAINT_ID NOT NULL,
	COMPLAINT_ID			NUMBER(10) NOT NULL,
	TOKEN_NO 				NUMBER(10),  
	FAULT_CODE 				VARCHAR2(20), 
	REGISTRATION_DATE_TIME	TIMESTAMP,
	SCOPE_CODE 				VARCHAR2(20), 
	CALL_STATUS				VARCHAR2(20), 
	LANDMARK 				VARCHAR2(100), 
	CONSUMER_CODE			VARCHAR2(20), 
	INCOMING_MOBILE			VARCHAR2(20), 
	COMPLAINT_CODE			VARCHAR2(20), 
	TRANSFER_DATE_TIME		TIMESTAMP, 
	TRANSFER_REMARK			VARCHAR2(250), 
	CATEGORY_CODE			VARCHAR2(20), 
	SUB_CATEGORY_CODE		VARCHAR2(20), 
	CLOSURE_DATE_TIME		TIMESTAMP, 
	CLOSURE_REMARK			VARCHAR2(250), 
	SRC						VARCHAR2(20), 
	STAFF_CODE				VARCHAR2(20), 
	STAFF_MOBILE			VARCHAR2(20), 
	STAFF_NAME				VARCHAR2(250),
	CREATED_BY				NUMBER(10) NOT NULL	
);

     
ALTER TABLE FOC_COMPLAINT ADD CONSTRAINT PK_FOC_COMPLAINT_ID PRIMARY KEY (ID);




--CALL CENTER MAPPING 

CREATE SEQUENCE CALL_CENTER_MAPPING_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;


CREATE TABLE CALL_CENTER_MAPPING (
	ID   					NUMBER(10) CONSTRAINT NN_CALL_CENTER_MAPPING_ID NOT NULL, 
	CALL_CENTER_USER_ID		NUMBER(10) NOT NULL CONSTRAINT FK_CALL_CENTER_USER_ID REFERENCES CALL_CENTER_USER ON DELETE CASCADE,
   	CIRCLE_ID				NUMBER(10) NOT NULL CONSTRAINT FK_CALL_CENTER_CIRCLE_ID REFERENCES CIRCLE ON DELETE CASCADE,
    CREATED_ON				TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON				TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE CALL_CENTER_MAPPING ADD CONSTRAINT PK_CALL_CENTER_MAPPING_ID PRIMARY KEY (ID);

--FIELD WORKER USER

CREATE SEQUENCE FIELD_WORKER_USER_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE FIELD_WORKER_USER (
	ID   				NUMBER(10) CONSTRAINT NN_FIELD_WORKER_USER_ID NOT NULL,
   	NAME 				VARCHAR2(100) CONSTRAINT NN_FIELD_WORKER_NAME NOT NULL,     
   	MOBILE		 		VARCHAR2(10) CONSTRAINT NN_FIELD_WORKER_MOBILE NOT NULL,
	REGION_ID			NUMBER(10) CONSTRAINT FK_FIELD_WORKER_REGION_ID REFERENCES REGION,
	SECTION_ID			NUMBER(10) NOT NULL CONSTRAINT FK_CALL_CENTER_SECTION_ID REFERENCES SECTION ON DELETE CASCADE,
	STAFF_CODE			VARCHAR2(15),
	STAFF_ROLE			VARCHAR2(10),
    CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL,
   	UPDATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE FIELD_WORKER_USER ADD CONSTRAINT PK_FIELD_WORKER_USER_ID PRIMARY KEY (ID);


--FIELD WORKER COMPLAINT

CREATE SEQUENCE FIELD_WORKER_COMP_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1 NOMAXVALUE NOCYCLE;
  
  
CREATE TABLE FIELD_WORKER_COMP (
	ID   				NUMBER(10) CONSTRAINT NN_FIELD_WORKER_COMP_ID NOT NULL,
   	FIELD_WORKER_ID		NUMBER(10),
	STATUS_ID			NUMBER(2),
	TRANSFER_DATE		TIMESTAMP,
	TRANSFER_FROM		NUMBER(10),
	COMPLAINT_ID		NUMBER(10) NOT NULL CONSTRAINT FK_FIELD_WORKER_COMP_ID REFERENCES COMPLAINT ON DELETE CASCADE,
    CREATED_ON			TIMESTAMP DEFAULT SYSDATE NOT NULL
);
     
ALTER TABLE FIELD_WORKER_COMP ADD CONSTRAINT PK_FIELD_WORKER_COMP_ID PRIMARY KEY (ID);