CREATE USER tangedcodemo IDENTIFIED BY tangedcodemo
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
	CREATE SYNONYM, CREATE PROCEDURE, CREATE TRIGGER
TO tangedcodemo;

CREATE USER tangedcopublic IDENTIFIED BY tangedcopublic
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE SYNONYM TO tangedcopublic;

CREATE USER tangedcopublicsms IDENTIFIED BY tangedcopublicsms
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE SYNONYM TO tangedcopublicsms;

CREATE USER tangedcoadmin IDENTIFIED BY tangedcoadmin
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE SYNONYM TO tangedcoadmin;

CREATE USER tangedcoadminsms IDENTIFIED BY tangedcoadminsms
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE SYNONYM TO tangedcoadminsms;

CREATE USER tangedcoconsumer IDENTIFIED BY tangedcoconsumer
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE SYNONYM TO tangedcoconsumer;

CREATE USER tangedcopublicsmsdev IDENTIFIED BY tangedcopublicsmsdev
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE SYNONYM TO tangedcopublicsmsdev;

CREATE USER tangedcoadminsmsdev IDENTIFIED BY tangedcoadminsmsdev
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE SYNONYM TO tangedcoadminsmsdev;

CREATE USER tangedcosmsadmin IDENTIFIED BY tangedcosmsadmin
	DEFAULT TABLESPACE SAMPLE_D1_128M
	TEMPORARY TABLESPACE TEMP
	QUOTA UNLIMITED ON SAMPLE_D1_128M
	QUOTA UNLIMITED ON SAMPLE_I1_128M;
	
	
GRANT CREATE SESSION, ALTER SESSION, CREATE SYNONYM TO tangedcosmsadmin;