-- Run Against tangedcopublic and tangedcoadmin

CREATE SYNONYM ADMIN_USER FOR tangedcodemo.ADMIN_USER;
CREATE SYNONYM CALL_CENTER_MAPPING FOR tangedcodemo.CALL_CENTER_MAPPING;
CREATE SYNONYM CALL_CENTER_ROLE FOR tangedcodemo.CALL_CENTER_ROLE;
CREATE SYNONYM CALL_CENTER_USER FOR tangedcodemo.CALL_CENTER_USER;
CREATE SYNONYM CATEGORY FOR tangedcodemo.CATEGORY;
CREATE SYNONYM CIRCLE FOR tangedcodemo.CIRCLE;
CREATE SYNONYM CLOSURE_REASON FOR tangedcodemo.CLOSURE_REASON;
CREATE SYNONYM COMPLAINT FOR tangedcodemo.COMPLAINT;
CREATE SYNONYM COMPLAINT_HISTORY FOR tangedcodemo.COMPLAINT_HISTORY;
CREATE SYNONYM CONSUMER_SERVICE FOR tangedcodemo.CONSUMER_SERVICE;
CREATE SYNONYM DISTRICT FOR tangedcodemo.DISTRICT;
CREATE SYNONYM DIVISION FOR tangedcodemo.DIVISION;
CREATE SYNONYM FIELD_WORKER_COMP FOR tangedcodemo.FIELD_WORKER_COMP;
CREATE SYNONYM FIELD_WORKER_USER FOR tangedcodemo.FIELD_WORKER_USER;
CREATE SYNONYM FOC_COMPLAINT FOR tangedcodemo.FOC_COMPLAINT;
CREATE SYNONYM PUBLIC_USER FOR tangedcodemo.PUBLIC_USER;
CREATE SYNONYM REGION FOR tangedcodemo.REGION;
CREATE SYNONYM RESCUE FOR tangedcodemo.RESCUE;
CREATE SYNONYM ROLE FOR tangedcodemo.ROLE;
CREATE SYNONYM SECTION FOR tangedcodemo.SECTION;
CREATE SYNONYM SMSGS FOR tangedcodemo.SMSGS;
CREATE SYNONYM SUB_CATEGORY FOR tangedcodemo.SUB_CATEGORY;
CREATE SYNONYM SUB_DIVISION FOR tangedcodemo.SUB_DIVISION;


CREATE SYNONYM ADMIN_USER_ID_SEQ FOR tangedcodemo.ADMIN_USER_ID_SEQ;
CREATE SYNONYM CALL_CENTER_MAPPING_ID_SEQ FOR tangedcodemo.CALL_CENTER_MAPPING_ID_SEQ;
CREATE SYNONYM CALL_CENTER_ROLE_ID_SEQ FOR tangedcodemo.CALL_CENTER_ROLE_ID_SEQ;
CREATE SYNONYM CALL_CENTER_USER_ID_SEQ FOR tangedcodemo.CALL_CENTER_USER_ID_SEQ;
CREATE SYNONYM CATEGORY_ID_SEQ FOR tangedcodemo.CATEGORY_ID_SEQ;
CREATE SYNONYM CIRCLE_ID_SEQ FOR tangedcodemo.CIRCLE_ID_SEQ;
CREATE SYNONYM CLOSURE_REASON_ID_SEQ FOR tangedcodemo.CLOSURE_REASON_ID_SEQ;
CREATE SYNONYM COMPLAINT_HISTORY_ID_SEQ FOR tangedcodemo.COMPLAINT_HISTORY_ID_SEQ;
CREATE SYNONYM COMPLAINT_ID_SEQ FOR tangedcodemo.COMPLAINT_ID_SEQ;
CREATE SYNONYM CONSUMER_SERVICE_ID_SEQ FOR tangedcodemo.CONSUMER_SERVICE_ID_SEQ;
CREATE SYNONYM DISTRICT_ID_SEQ FOR tangedcodemo.DISTRICT_ID_SEQ;
CREATE SYNONYM DIVISION_ID_SEQ FOR tangedcodemo.DIVISION_ID_SEQ;
CREATE SYNONYM FIELD_WORKER_COMP_ID_SEQ FOR tangedcodemo.FIELD_WORKER_COMP_ID_SEQ;
CREATE SYNONYM FIELD_WORKER_USER_ID_SEQ FOR tangedcodemo.FIELD_WORKER_USER_ID_SEQ;
CREATE SYNONYM FOC_COMPLAINT_ID_SEQ FOR tangedcodemo.FOC_COMPLAINT_ID_SEQ;
CREATE SYNONYM ORDER_CUSTOM_NUMBER_SEQ FOR tangedcodemo.ORDER_CUSTOM_NUMBER_SEQ;
CREATE SYNONYM PUBLIC_USER_ID_SEQ FOR tangedcodemo.PUBLIC_USER_ID_SEQ;
CREATE SYNONYM REGION_ID_SEQ FOR tangedcodemo.REGION_ID_SEQ;
CREATE SYNONYM RESCUE_ID_SEQ FOR tangedcodemo.RESCUE_ID_SEQ;
CREATE SYNONYM ROLE_ID_SEQ FOR tangedcodemo.ROLE_ID_SEQ;
CREATE SYNONYM SECTION_ID_SEQ FOR tangedcodemo.SECTION_ID_SEQ;
CREATE SYNONYM SMSGS_ID_SEQ FOR tangedcodemo.SMSGS_ID_SEQ;
CREATE SYNONYM SUB_CATEGORY_ID_SEQ FOR tangedcodemo.SUB_CATEGORY_ID_SEQ;
CREATE SYNONYM SUB_DIVISION_ID_SEQ FOR tangedcodemo.SUB_DIVISION_ID_SEQ;

CREATE SYNONYM VIEW_COMPLAINT FOR tangedcodemo.VIEW_COMPLAINT;
CREATE SYNONYM VIEW_COMPLAINT_REMARK FOR tangedcodemo.VIEW_COMPLAINT_REMARK;
CREATE SYNONYM VIEW_COMPLAINT_REPORT FOR tangedcodemo.VIEW_COMPLAINT_REPORT;
CREATE SYNONYM VIEW_LOCATION FOR tangedcodemo.VIEW_LOCATION;

-- Run Against tangedcoconsumer

CREATE SYNONYM SECTION FOR tangedcodemo.SECTION;


-- Run Against tangedcopublicsms tangedcoadminsms tangedcopublicsmsdev tangedcoadminsmsdev tangedcosmsadmin

CREATE SYNONYM SMSGS FOR tangedcodemo.SMSGS;
CREATE SYNONYM SMSGS_ID_SEQ FOR tangedcodemo.SMSGS_ID_SEQ;