INSERT INTO CATEGORY (ID, NAME, RESCUE_ID, CREATED_ON, UPDATED_ON) VALUES (CATEGORY_ID_SEQ.nextval, 'Service Related Complaint', 1, sysdate, sysdate);
INSERT INTO SUB_CATEGORY (ID, NAME, CATEGORY_ID, CREATED_ON, UPDATED_ON) VALUES 
(SUB_CATEGORY_ID_SEQ.nextval, 'New Service Connection', (SELECT ID FROM CATEGORY WHERE NAME = 'Service Related Complaint'), sysdate, sysdate);
INSERT INTO SUB_CATEGORY (ID, NAME, CATEGORY_ID, CREATED_ON, UPDATED_ON) VALUES 
(SUB_CATEGORY_ID_SEQ.nextval, 'Additional / Reduction of Load', (SELECT ID FROM CATEGORY WHERE NAME = 'Service Related Complaint'), sysdate, sysdate);
INSERT INTO SUB_CATEGORY (ID, NAME, CATEGORY_ID, CREATED_ON, UPDATED_ON) VALUES 
(SUB_CATEGORY_ID_SEQ.nextval, 'Temporary Supply', (SELECT ID FROM CATEGORY WHERE NAME = 'Service Related Complaint'), sysdate, sysdate);
INSERT INTO SUB_CATEGORY (ID, NAME, CATEGORY_ID, CREATED_ON, UPDATED_ON) VALUES 
(SUB_CATEGORY_ID_SEQ.nextval, 'Name Transfer', (SELECT ID FROM CATEGORY WHERE NAME = 'Service Related Complaint'), sysdate, sysdate);
INSERT INTO SUB_CATEGORY (ID, NAME, CATEGORY_ID, CREATED_ON, UPDATED_ON) VALUES 
(SUB_CATEGORY_ID_SEQ.nextval, 'Solar Net metering', (SELECT ID FROM CATEGORY WHERE NAME = 'Service Related Complaint'), sysdate, sysdate);
INSERT INTO SUB_CATEGORY (ID, NAME, CATEGORY_ID, CREATED_ON, UPDATED_ON) VALUES 
(SUB_CATEGORY_ID_SEQ.nextval, 'Agricultural Service', (SELECT ID FROM CATEGORY WHERE NAME = 'Service Related Complaint'), sysdate, sysdate);


INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'New / Temp Supply Service effected');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Additional / Reduction of Load effected');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Name Transfer completed');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Solar Meter fixed');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Pending Payment to be cleared');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Road cut issues, will be sorted out soon');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Application cancelled. Please check portal');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Old arrears pending to be cleared');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Discrepancy in Application. Notice issued');
INSERT INTO CLOSURE_REASON (ID, COMPLAINT_CODE, REASON) VALUES (CLOSURE_REASON_ID_SEQ.nextval, 7,'Others');